Fix crash under Windows
If you remove the last serial interface under windows, gattii crashes. This fix handles
the access to the HashMap more carefully.

Backtrace of error:
```
thread 'main' panicked at 'no entry found for key', /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\libstd\collections\hash\map.rs:1023:9
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:59
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:470
  11: rust_begin_unwind
             at src\libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src\libcore/panicking.rs:85
  13: core::option::expect_failed
             at src\libcore/option.rs:1203
  14: core::option::Option<T>::expect
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\libcore/option.rs:347
  15: <std::collections:#:map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\libstd\collections\hash/map.rs:1023
  16: gattii::receive::{{closure}}
             at src\bin/gattii.rs:1264
  17: std:¿?:local::LocalKey<T>::try_with
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\libstd\thread/local.rs:262
  18: std:¿?:local::LocalKey<T>::with
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\libstd\thread/local.rs:239
  19: gattii::receive
             at src\bin/gattii.rs:979
  20: core::ops::function::FnMut::call_mut
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\libcore\ops/function.rs:154
  21: glib::source::trampoline
             at C:\Users\pulp\.cargo\registry\src\github.com-1ecc6299db9ec823\glib-0.7.0\src/source.rs:104
  22: unit_addrs_search
  23: unit_addrs_search
  24: unit_addrs_search
  25: unit_addrs_search
  26: gtk::auto::functions::main
             at C:\Users\pulp\.cargo\registry\src\github.com-1ecc6299db9ec823\gtk-0.6.0\src\auto/functions.rs:260
  27: gattii::main
             at src\bin/gattii.rs:219
  28: std::rt::lang_start::{{closure}}
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\libstd/rt.rs:67
  29: std::rt::lang_start_internal::{{closure}}
             at src\libstd/rt.rs:52
  30: std::panicking::try::do_call
             at src\libstd/panicking.rs:303
  31: __rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:86
  32: std::panicking::try
             at src\libstd/panicking.rs:281
  33: std::panic::catch_unwind
             at src\libstd/panic.rs:394
  34: std::rt::lang_start_internal
             at src\libstd/rt.rs:51
  35: std::rt::lang_start
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\libstd/rt.rs:67
  36: main
  37: __tmainCRTStartup
             at D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:335
  38: mainCRTStartup
             at D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:219
  39: unit_addrs_search
  40: unit_addrs_search
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\gattii.exe` (exit code: 101)
```